# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7985867fc87761ebcd867c2074a36325f9f16238f11e1122a3dc611a4dbd1cf32f861cebcd1df5e449e728aebd7fcf06b3e779a80d4aedeb2808700d022a0b2e

test:
  secret_key_base: b049da11b7d34ba82e6926813e9f70bdc5c947f45a75cd5c95fa81f2d59509292b7dbda6194da8618e1564335584c6b6e678a156be59ee1bb22d84ccb7468870

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
